=== nourhanali010/ITI-java-project-chatMessenger/project/ClientJavaProject/build/classes/XMLMODEL/history.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="history" type="historyType"/>

    <xs:complexType name="historyType">
        <xs:sequence>
            <xs:element name="message" type="MessageType" maxOccurs="unbounded" />    
        </xs:sequence>
        <xs:attribute name="owner" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="MessageType">
        <xs:sequence>
            <xs:element name="from" type="xs:string"/>
            <xs:element name="to" type="xs:string"/>
            <xs:element name="size" type="xs:int"/>
            <xs:element name="body" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="fontSize">
        <xs:restriction base="xs:positiveInteger">
            <xs:minExclusive value="8"/>
            <xs:maxExclusive value="24"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="fontFamily">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Arial"/>
        </xs:restriction>
    </xs:simpleType>
    
    
</xs:schema>

=== nourhanali010/ITI-java-project-chatMessenger/project/ClientJavaProject/XMLMODEL/history.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='history.xsl'?>
<history xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" owner="nour@gmail.com" xsi:noNamespaceSchemaLocation="history.xsd">
    <message>
        <from>asmaa@gmail</from>
        <to>nour@gmail.com</to>
        <size>0</size>
        <body>hey</body>
    </message>
    <message>
        <from>nour@gmail.com</from>
        <to>asmaa@gmail</to>
        <size>0</size>
        <body>how are u</body>
    </message>
</history>

=== nourhanali010/ITI-java-project-chatMessenger/project/ClientJavaProject/build/classes/XMLMODEL/history.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='history.xsl'?>
<history xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" owner="aa@gmail.com" xsi:noNamespaceSchemaLocation="history.xsd">
    <message>
        <from>we@gmail.com</from>
        <to>aa@gmail.com</to>
        <size>0</size>
        <body>oio</body>
    </message>
    <message>
        <from>we@gmail.com</from>
        <to>aa@gmail.com</to>
        <size>0</size>
        <body>klkkl</body>
    </message>
    <message>
        <from>we@gmail.com</from>
        <to>aa@gmail.com</to>
        <size>0</size>
        <body>hi </body>
    </message>
    <message>
        <from>we@gmail.com</from>
        <to>aa@gmail.com</to>
        <size>0</size>
        <body>ahmed </body>
    </message>
    <message>
        <from>we@gmail.com</from>
        <to>aa@gmail.com</to>
        <size>0</size>
        <body>fgghyyuuy</body>
    </message>
    <message>
        <from>we@gmail.com</from>
        <to>aa@gmail.com</to>
        <size>0</size>
        <body>hhg</body>
    </message>
    <message>
        <from>we@gmail.com</from>
        <to>aa@gmail.com</to>
        <size>0</size>
        <body>hhjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj</body>
    </message>
    <message>
        <from>we@gmail.com</from>
        <to>aa@gmail.com</to>
        <size>0</size>
        <body>uiiiiiiiiiiiiiiiii</body>
    </message>
    <message>
        <from>aa@gmail.com</from>
        <to>we@gmail.com</to>
        <size>0</size>
        <body>uiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii</body>
    </message>
    <message>
        <from>aa@gmail.com</from>
        <to>we@gmail.com</to>
        <size>0</size>
        <body>ssdd</body>
    </message>
    <message>
        <from>aa@gmail.com</from>
        <to>we@gmail.com</to>
        <size>0</size>
        <body>jhkjhjh</body>
    </message>
</history>
